In [13]:
import numpy as np
A = np.array([[20,0,4,86],
              [50,21,0.3,8],
              [30,35,90,21]
              ])
print(A)

[[20.   0.   4.  86. ]
 [50.  21.   0.3  8. ]
 [30.  35.  90.  21. ]]


In [15]:
cal = A.sum(axis=0)

print(cal)

[100.   56.   94.3 115. ]


In [17]:
percentage = 100*A/cal
print(percentage)


[[20.          0.          4.24178155 74.7826087 ]
 [50.         37.5         0.31813362  6.95652174]
 [30.         62.5        95.44008484 18.26086957]]


In [26]:
a= np.array([[1,2,3]])
b= np.array([[4,5,6]])
print(b)
print(b.T)
print(np.dot(a,b.T))
print(a+b.T)

[[4 5 6]]
[[4]
 [5]
 [6]]
[[32]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [32]:
#r = np.random.randn(5) # rank 1 array don't use these
# you can reshape a.reshape(5,1)
r = np.random.randn(5,1) #use this or (1,5)


# a=np.random.rand(1,3)
# b=np.random.rand(3,3)
a=np.array([[1,2,3]])
b=np.array([[1,2,3],[1,1,1],[2,2,2]])
print(a)
print(b)
print(b*a)
print(a*b)
print(np.dot(a,b))

[[1 2 3]]
[[1 2 3]
 [1 1 1]
 [2 2 2]]
[[1 4 9]
 [1 2 3]
 [2 4 6]]
[[1 4 9]
 [1 2 3]
 [2 4 6]]
[[ 9 10 11]]
