For -1 as param in the dimestions.. the functions automatically determines the shape based on the total number of elements that fits for the reshaped array..


In [3]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Reshape the array to have 3 columns and automatically infer the number of rows
reshaped_arr = np.reshape(arr, (-1, 2)) 


print("Original array:")
print(arr)
print("Reshaped array:")
print(reshaped_arr)




Original array:
[[1 2 3]
 [4 5 6]]
Reshaped array:
[[1 2]
 [3 4]
 [5 6]]
